### ISSUE TITLE
undefined reference to `ti_lib_gpio_clear_dio'

### ISSUE THREAD

**Issue by ghazel** [Telecontrolli/6lbr-on-Telecontrolli-Devices-XIP#1]
Instructions say to use `develop-20170121` tag for 6lbr: https://github.com/Telecontrolli/6lbr-on-Telecontrolli-Devices-XIP/blame/f50b80fb589ac7cb2130f1cd32c53e8fa8e7af37/README.md#L26

However, `6lbr-on-Telecontrolli-Devices-XIP` references `ti_lib_gpio_read_dio` https://github.com/Telecontrolli/6lbr-on-Telecontrolli-Devices-XIP/blob/master/srf06-cc26xx/srf06/button-sensor.c#L58 which is not defined as of the `develop-20170121` tag: https://github.com/cetic/6lbr/blob/develop-20170121/cpu/cc26xx-cc13xx/ti-lib.h

**Comment by MarCast** [comment]
Try refer to: https://github.com/Telecontrolli/6lbr-on-Telecontrolli-Devices-XIP/blob/master/6lbr%20installation%20procedure.pdf
